R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
];

R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
];

R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
	"land_misc_cargo1a_ep1",
	"land_misc_cargo1ao",
	"land_misc_cargo1ao_ep1",
	"land_misc_cargo1b",
	"land_misc_cargo1b_ep1",
	"land_misc_cargo1bo",
	"land_misc_cargo1c",
	"land_misc_cargo1c_ep1",
	"land_misc_cargo1d",
	"land_misc_cargo1d_ep1",
	"land_misc_cargo1e",
	"land_misc_cargo1e_ep1",
	"land_misc_cargo1f",
	"land_misc_cargo1g",
	"land_misc_cargomarket1a_ep1",
	"base_warfarebcontructionsite",
	"misc_cargo_cont_net1",
	"misc_cargo_cont_small",
	"misc_cargo_cont_small2"
];

R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
	["land_misc_cargo1ao", 110],
	["land_misc_cargo1a_ep1", 110],
	["land_misc_cargo1ao_ep1", 110],
	["land_misc_cargo1b", 110],
	["land_misc_cargo1b_ep1", 110],
	["land_misc_cargo1bo", 110],
	["land_misc_cargo1c", 110],
	["land_misc_cargo1c_ep1", 110],
	["land_misc_cargo1d", 110],
	["land_misc_cargo1d_ep1", 110],
	["land_misc_cargo1e", 110],
	["land_misc_cargo1e_ep1", 110],
	["land_misc_cargo1f", 110],
	["land_misc_cargo1g", 110],
	["land_misc_cargomarket1a_ep1", 110],
	["base_warfarebcontructionsite", 110],
	["fortress2", 20],
	["warfarebcamp", 30],
	["misc_cargo_cont_small", 65],
	["misc_cargo_cont_small2", 50]
];

R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
	["concrete_wall_ep1", 3],
	["fencewood", 1],
	["fencewoodpalet", 1],
	["wire", 2],
	["fire", 1],
	["flagcarriersmall", 1],
	["fort_razorwire", 2],
	["gunrack1", 2],
	["base_warfarebbarrier5x", 3],
	["base_warfarebbarrier10x", 6],
	["base_warfarebbarrier10xtall", 12],
	["base_warfarebbarrier5xpreview", 2],
	["land_camonet_east", 2],
	["land_camonet_nato", 2],
	["land_fire", 1],
	["land_fire_barrel", 3],
	["land_fort_watchtower", 20],
	["land_guardshed", 3],
	["land_misc_cargo1ao", 120],
	["land_misc_cargo1a_ep1", 120],
	["land_misc_cargo1ao_ep1", 120],
	["land_misc_cargo1b", 120],
	["land_misc_cargo1b_ep1", 120],
	["land_misc_cargo1bo", 120],
	["land_misc_cargo1c", 120],
	["land_misc_cargo1c_ep1", 120],
	["land_misc_cargo1d", 120],
	["land_misc_cargo1d_ep1", 120],
	["land_misc_cargo1e", 120],
	["land_misc_cargo1e_ep1", 120],
	["land_misc_cargo1f", 120],
	["land_misc_cargo1g", 120],
	["land_misc_cargomarket1a_ep1", 120],
	["land_woodenramp", 2],
	["land_fort_bagfence_corner", 3],
	["land_fort_bagfence_long", 2],
	["land_fort_bagfence_round", 4],
	["land_fort_rampart", 4],
	["land_fortified_nest_big", 20],
	["land_fortified_nest_small", 10],
	["land_cncblock", 2],
	["land_cncblock_d", 2],
	["land_cncblock_stripes", 2],
	["land_hbarrier_large", 4],
	["land_bagfencecorner", 2],
	["land_hbarrier1", 1],
	["land_hbarrier3", 2],
	["land_hbarrier5", 3],
	["land_toilet", 3],
	["paletabase", 2],
	["roadbarrier_light", 2],
	["targettraining", 2],
	["warfarebunkersign", 3],
	["zavoraanim", 2],
	["base_warfarebcontructionsite", 120],
	["fortress1", 10],
	["hedgehog", 3],
	["land_prebehlavka", 3],
	["land_prolejzacka", 2],
	["ammocrate_nointeractive_", 7],
	["misc_cargo_cont_net1", 25],
	["misc_cargo_cont_small", 75],
	["misc_cargo_cont_small2", 60],
	["shed", 2],
	["target", 2],

	["Land_CzechHedgehog_01_F", 2],

    ["Land_Bunker_01_blocks_3_F", 30],
    ["Land_Bunker_01_big_F", 120],
    ["Land_Bunker_01_blocks_1_F", 10],
    ["Land_Bunker_01_HQ_F", 120],
    ["Land_Bunker_01_small_F", 50],
    ["Land_Bunker_01_tall_F", 75],

    ["Land_SandbagBarricade_01_half_F", 2],
    ["Land_SandbagBarricade_01_F", 2],
    ["Land_SandbagBarricade_01_hole_F", 2],

    ["Land_BagBunker_Large_F", 20],
    ["Land_BagBunker_Small_F", 10],
    ["Land_BagBunker_Tower_F", 10],

    ["CamoNet_INDP_F", 4],
    ["CamoNet_INDP_open_F", 4],

    ["Land_MedicalTent_01_MTP_closed_F", 4],

    ["Land_Cargo_House_V1_F", 50],
    ["Land_Cargo_HQ_V1_F", 75],
    ["Land_Cargo_Patrol_V1_F", 50],
    ["Land_Cargo_Tower_V1_F", 120],

    ["Land_CncShelter_F", 4],

    ["Hhedgehog_concreteBig", 4],
    ["Hhedgehog_concrete", 4],

    ["Land_Vez", 10],
    ["Land_Hlaska", 10],

    ["Land_Mil_WallBig_4m_F", 7],
    ["Land_Mil_WallBig_Corner_F", 7],

    ["Land_CncBarrier_F", 4],
    ["Land_CncBarrierMedium_F", 4],
    ["Land_CncBarrier_stripes_F", 4],
    ["Land_CncBarrierMedium4_F", 4],

    ["Land_BarGate_F", 2]
];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
	"concrete_wall_ep1",
	"fencewood",
	"fencewoodpalet",
	"wire",
	"fire",
	"flagcarriersmall",
	"fort_razorwire",
	"gunrack1",
	"base_warfarebbarrier5x",
	"land_camonet_east",
	"land_camonet_nato",
	"land_fire",
	"land_fort_watchtower",
	"land_guardshed",
	"land_woodenramp",
	"land_fort_bagfence_corner",
	"land_fort_bagfence_long",
	"land_fort_bagfence_round",
	"land_fort_rampart",
	"land_fortified_nest_big",
	"land_fortified_nest_small",
	"land_cncblock",
	"land_cncblock_d",
	"land_cncblock_stripes",
	"land_hbarrier_large",
	"land_bagfencecorner",
	"land_toilet",
	"paletabase",
	"roadbarrier_light",
	"targettraining",
	"warfarebunkersign",
	"zavoraanim",
	"fortress1",
	"hedgehog",
	"land_prebehlavka",
	"land_prolejzacka",
	"ammocrate_nointeractive_",
	"misc_cargo_cont_net1",
	"shed",
	"target",

	"Land_CzechHedgehog_01_F",
    "Land_Barricade_01_10m_F",
    "Land_Barricade_01_4m_F",
    "Land_Bunker_01_blocks_3_F",
    "Land_Bunker_01_big_F",
    "Land_Bunker_01_blocks_1_F",
    "Land_Bunker_01_HQ_F",
    "Land_Bunker_01_small_F",
    "Land_Bunker_01_tall_F",
    "Land_SandbagBarricade_01_half_F",
    "Land_SandbagBarricade_01_F",
    "Land_SandbagBarricade_01_hole_F",
    "Land_BagBunker_Large_F",
    "Land_BagBunker_Small_F",
    "Land_BagBunker_Tower_F",
    "CamoNet_INDP_F",
    "CamoNet_INDP_open_F",
    "Land_MedicalTent_01_MTP_closed_F",
    "Land_Cargo_House_V1_F",
    "Land_Cargo_HQ_V1_F",
    "Land_Cargo_Patrol_V1_F",
    "Land_Cargo_Tower_V1_F",
    "Land_CncShelter_F",
    "Hhedgehog_concreteBig",
    "Hhedgehog_concrete",
    "Land_Vez",
    "Land_Hlaska",
    "Land_Mil_WallBig_4m_F",
    "Land_Mil_WallBig_Corner_F",
    "Land_CncBarrier_F",
    "Land_CncBarrierMedium_F",
    "Land_CncBarrier_stripes_F",
    "Land_CncBarrierMedium4_F",
    "Land_BarGate_F"
];